apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client
spec:
  commonName: client.${jkube.namespace}.vault.int.company.io
  dnsNames:
    - client.${jkube.namespace}.vault.int.company.io
    - client.${jkube.namespace}.svc
    - client-${jkube.namespace}.apps.cluster-8dl2g.8dl2g.sandbox1725.opentlc.com
  issuerRef:   
    name: ${jkube.namespace}-issuer-vault
  secretName: client
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: client-keystore-pass

