apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
  namespace: vault-config-operator
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: controller-manager
  type: kubernetes
  path: app-kubernetes
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineConfig
metadata:
  name: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  namespace: vault-config-operator
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: controller-manager
  tokenReviewerServiceAccount:
    name: controller-manager
  path: app-kubernetes
  disableISSValidation: True
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
  namespace: vault-config-operator
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: controller-manager
  path: app-kubernetes/{{ .Release.Namespace }}
  policies:
  - "{{ .Release.Namespace }}-pki-engine"
  targetServiceAccounts:
  - default
  targetNamespaces:
    targetNamespaces:
    - "{{ .Release.Namespace }}"
