---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: "{{ .Release.Namespace }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  authentication:
    path: app-kubernetes/{{ .Release.Namespace }}
    role: "{{ .Release.Namespace }}"
  type: pki
  path: app-pki
  config:
    # 1 Year
    maxLeaseTTL: "8760h"
