secretCA: intermediate

base:
  nameOverride: vault
  global:
    tlsDisable: false
    openshift: true
  injector:
    enabled: false
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
      tag: "0.14.2-ubi"
      #tag: "0.16.1-ubi"
    agentImage:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.9.10-ubi"
      #tag: "1.12.1-ubi"
    webhook:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
  ui:
    enabled: true

  serverTelemetry:
    prometheusRules:
      enabled: false

  server:
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.9.10-ubi"
      #tag: "1.12.1-ubi"
    route:
      enabled: true
      annotations:
        "redhat-cop.redhat.io/patch": |
          spec:
            host: {{ (lookup "config.openshift.io/v1" "DNS" .metadata.name "cluster").spec.baseDomain }}
      host: vault.apps.cluster-7kkcp.7kkcp.sandbox601.opentlc.com
    extraEnvironmentVars:
      VAULT_CACERT: "/etc/vault-tls/vault-certs/ca.crt"
      VAULT_TLS_SERVER_NAME:
    standalone:
      enabled: false
    auditStorage:
      enabled: true
      size: 15Gi
    extraVolumes:
      - type: "secret"
        name: "vault-certs"
        path: "/etc/vault-tls"
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/etc/vault-tls/vault-certs/tls.crt"
            tls_key_file = "/etc/vault-tls/vault-certs/tls.key"
            tls_client_ca_file = "/etc/vault-tls/vault-certs/ca.crt"
          }
          storage "raft" {
            path = "/vault/data"
            retry_join {
              leader_api_addr = "https://vault-active.hashicorp-vault.svc:8200"
              leader_ca_cert_file = "/etc/vault-tls/vault-certs/ca.crt"
            }
          }
          log_level = "debug"
          service_registration "kubernetes" {}
    service:
      enabled: true


bootstrap:
  oc:
    image:
      repository: quay.io/openshift/origin-cli
      pullPolicy: IfNotPresent
      tag: 4.11
  vault:
    image:
      repository: registry.connect.redhat.com/hashicorp/vault
      tag: "1.9.2-ubi"
    init: true
    auth: False
  serviceAccount:
    name: "vault-bootstrap"

#  init:
#    annotations:
#      argocd.argoproj.io/sync-wave: "1"
#  unsealed:
#    annotations:
#      argocd.argoproj.io/sync-wave: "1"
  auth:
    annotations:
      argocd.argoproj.io/sync-wave: "2"