apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server
spec:
  commonName: server.${jkube.namespace}.vault.int.company.io
  dnsNames:
    - server.${jkube.namespace}.vault.int.company.io
    - server.${jkube.namespace}.svc
    - server-${jkube.namespace}.apps.cluster-8dl2g.8dl2g.sandbox1725.opentlc.com
  issuerRef:
    name: ${jkube.namespace}-issuer-vault
  secretName: server
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: server-keystore-pass

